name: GitBook Continuous Integration

on:
  workflow_run:
    workflows: ["README Continuous Integration"]
    types:
      - completed

jobs:
  GitBook-CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SUMMARY.md
        run: echo -e "# Table of contents\\n\\n* [Summary](README.md)"> ./SUMMARY.md

      - name: Look for Lecture Notes
        id: LN
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "${{ github.event.repository.name }} Lecture Notes.tex"
      
      - name: Look for Exam Notes
        id: EN
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "${{ github.event.repository.name }} Exam Notes.tex"

      - if: steps.LN.outputs.files_exists == 'true'
        name: Convert Lecture Notes to HTML
        uses: docker://pandoc/core:latest
        with:
          args: --from latex --to html --mathjax -s "${{ github.event.repository.name }} Lecture Notes.tex" -o "${{ github.event.repository.name }} Lecture Notes.html"

      - if: steps.LN.outputs.files_exists == 'true'
        name: Update SUMMARY
        run: echo "* [Lecture Notes](${{ github.event.repository.name }} Lecture Notes.html)" >> SUMMARY.md
      
      - if: steps.EN.outputs.files_exists == 'true'
        name: Convert Exam Notes to HTML
        uses: docker://pandoc/core:latest
        with:
          args: --from latex --to html --mathjax -s "${{ github.event.repository.name }} Exam Notes.tex" -o "${{ github.event.repository.name }} Exam Notes.html"

      - if: steps.EN.outputs.files_exists == 'true'
        name: Update SUMMARY
        run: echo "* [Exam Notes](${{ github.event.repository.name }} Exam Notes.html)" >> SUMMARY.md

      - name: Push files to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "GitBook CI"
          git push
