name: Update parent repository

on:
  workflow_run:
    workflows: ["README Continuous Integration"]
    types:
      - completed

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          repository: Tarang74/QUT-Notes
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}

      - name: Pull & update submodules
        run: |
          git submodule update --init ${{ github.event.repository.name }}
          git submodule update --remote ${{ github.event.repository.name }}
      
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
